/* eslint-disable no-unused-vars */
import { AuthState } from "@/interfaces/redux";
import { createSlice } from "@reduxjs/toolkit";

const initialState: AuthState = { email: null, username: null, token: null, isAuthenticated: false }

// createSlice allows you to define the Redux state slice in a single function,
// including the initial state, reducers, and action creators, making it easier to manage state and actions.
// when you create a slice using the createSlice function, it generates two key things: actions and reducer.
const authSlice = createSlice({
    name: "auth", // The name of the slice
    initialState: initialState, // The initial state of the slice
    // reducer functions are accepting the previous state and the action and return the new state
    reducers: {
        login(state, action: {"payload": {username: string, email: string, token: string}}) {
            state.username = action.payload.username;
            state.token = action.payload.token;
            state.email = action.payload.email;
            state.isAuthenticated = true;
        },
        logout(state) {
            state.username = null;
            state.token = null;
            state.email = null;
            state.isAuthenticated = false;
        },
        setToken(state, action) {
            state.token = action.payload.token;
        },
        setUsername(state, action) {
            state.username = action.payload.username
        },
        setEmail(state, action) {
            state.email = action.payload.email
        },
        setIsAuthenticated(state, action) {
            state.isAuthenticated = action.payload.isAuthenticated
        }
    }
})

// Redux Toolkit will generate action creators for each reducer that you have defined in your slice.
// cartSlice.actions is an object that contains those action creators.
// Here, we extract these specific action creators from the actions object,
// and export them available for import in other files.
export const { login, logout, setEmail, setUsername, setIsAuthenticated, setToken } = authSlice.actions;

// This line exports the reducer function generated by the createSlice function as the default export from the module.
export default authSlice.reducer;
